"""
Merge a research delta package into the local SQLite database.

Use this after Google Drive sync has downloaded a package generated by
scripts/export_incremental_research.py.
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
from pathlib import Path

try:
    from scripts.init_db import init_db
except ModuleNotFoundError:
    from init_db import init_db  # type: ignore


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def table_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    return {str(row[1]) for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}


def resolve_package(path: Path) -> Path:
    if (path / "manifest.json").exists():
        return path
    candidates = sorted(
        [p for p in path.iterdir() if p.is_dir() and (p / "manifest.json").exists()],
        key=lambda p: p.name,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError(f"No manifest.json found under {path}")
    return candidates[0]


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def merge_table(conn: sqlite3.Connection, table: str, csv_path: Path) -> int:
    rows = load_csv_rows(csv_path)
    if not rows:
        return 0

    valid_columns = table_columns(conn, table)
    if not valid_columns:
        return 0

    columns = [column for column in rows[0].keys() if column in valid_columns]
    if not columns:
        return 0

    placeholders = ", ".join(["?"] * len(columns))
    column_sql = ", ".join(columns)
    sql = f"INSERT OR REPLACE INTO {table} ({column_sql}) VALUES ({placeholders})"

    values = []
    for row in rows:
        values.append([row.get(column) if row.get(column) != "" else None for column in columns])
    conn.executemany(sql, values)
    return len(values)


def import_delta(package_path: Path) -> dict[str, int]:
    package = resolve_package(package_path)
    manifest = json.loads((package / "manifest.json").read_text(encoding="utf-8"))
    db_path = init_db()
    imported: dict[str, int] = {}

    with sqlite3.connect(str(db_path)) as conn:
        conn.execute("PRAGMA journal_mode=WAL;")
        for table in manifest.get("tables", []):
            table_name = str(table["name"])
            imported[table_name] = merge_table(conn, table_name, package / str(table["csv_file"]))
        conn.commit()

    return imported


def main() -> None:
    parser = argparse.ArgumentParser(description="Import a research delta package into SQLite.")
    parser.add_argument(
        "package",
        nargs="?",
        default=str(project_root() / "research_deltas"),
        help="Delta package directory, or a parent directory containing packages.",
    )
    args = parser.parse_args()

    imported = import_delta(Path(args.package).expanduser())
    total = sum(imported.values())
    print(f"Imported rows: {total}")
    for table, count in imported.items():
        print(f"  {table}: {count}")


if __name__ == "__main__":
    main()
